Fix FPC compilation
It cannot compile due to:

  Error: Incompatible types: got "AnsiString" expected "Extended"

Also revert to previous order of checks for old Delphi. Better to not
depend that old Delphis support CompilerVersion or even $IF.